"""
Code generation and editing capability for MKAngel.

Uses the Angel's computational grammar to assist with code --
analysing structure, generating from natural language descriptions,
refactoring, and explaining code through grammatical rules.
"""

from __future__ import annotations

import textwrap
from typing import Any


class Coder:
    """Code assistant powered by the Grammar Language Model.

    Uses the computational grammar (syntax, types, patterns) to
    understand and generate code from structural first principles.
    Can also route through an LLM provider for richer generation.
    """

    def __init__(self, provider=None):
        """Initialise the coder.

        Args:
            provider: An LLM provider instance (from app.providers).
                      If None, uses the local GLM grammar engine directly.
        """
        self._provider = provider
        self._angel = None

    def _get_angel(self):
        """Lazy-load the Angel for grammar operations."""
        if self._angel is None:
            from glm.angel import Angel
            self._angel = Angel()
            self._angel.awaken()
        return self._angel

    # ------------------------------------------------------------------
    # Core operations
    # ------------------------------------------------------------------

    def generate_code(self, description: str, language: str = "python") -> str:
        """Generate code from a natural language description.

        Uses the computational grammar to derive code structure,
        then either the local GLM or an API provider for implementation.

        Args:
            description: What the code should do.
            language: Target programming language.

        Returns:
            Generated code as a string.
        """
        if self._provider is not None:
            system_prompt = (
                f"You are a code generator. Write clean, well-commented "
                f"{language} code. Only output the code, no explanation. "
                f"Use proper formatting and follow best practices."
            )
            return self._provider.generate(
                f"Generate {language} code: {description}",
                system=system_prompt,
                temperature=0.3,
                max_tokens=2048,
            )

        # Local GLM path: use computational grammar for structure
        angel = self._get_angel()
        tokens = description.lower().split()

        try:
            predictions = angel.predict(tokens, domain="computational", horizon=10)
        except Exception:
            predictions = []

        lines = [f"# Generated by MKAngel GLM ({language})"]
        lines.append(f"# Description: {description}")
        lines.append(f"# Grammar derivation from computational domain")
        lines.append("")

        if predictions:
            lines.append("# Structural analysis:")
            for i, pred in enumerate(predictions[:8], 1):
                rule = pred.get("rule", "?")
                output = pred.get("predicted", "?")
                conf = pred.get("confidence", 0.0)
                lines.append(f"#   {i}. rule={rule} -> {output} (conf={conf:.2f})")
            lines.append("")

            # Derive a code skeleton from grammar rules
            lines.append(_derive_skeleton(description, language, predictions))
        else:
            lines.append(_derive_skeleton(description, language, []))

        lines.append("")
        lines.append(
            "# Note: For richer code generation, configure an API provider."
        )
        return "\n".join(lines)

    def analyze_code(self, code: str) -> dict[str, Any]:
        """Analyse code using the computational grammar.

        Examines structure, patterns, and types through grammatical
        rules rather than statistical heuristics.

        Args:
            code: Source code to analyse.

        Returns:
            Analysis results as a dictionary.
        """
        if self._provider is not None:
            raw = self._provider.generate(
                f"Analyse this code. Report: structure, patterns, "
                f"potential issues, and complexity.\n\n```\n{code}\n```",
                system=(
                    "You are a code analyst. Provide structured analysis "
                    "covering: structure, patterns used, potential issues, "
                    "and overall complexity. Be concise."
                ),
                temperature=0.2,
                max_tokens=1024,
            )
            return {
                "analysis": raw,
                "source": "api",
                "provider": getattr(self._provider, "name", "unknown"),
            }

        # Local grammar analysis
        angel = self._get_angel()
        lines = code.strip().splitlines()

        # Basic structural metrics
        total_lines = len(lines)
        blank_lines = sum(1 for ln in lines if not ln.strip())
        comment_lines = sum(
            1 for ln in lines
            if ln.strip().startswith("#") or ln.strip().startswith("//")
        )
        code_lines = total_lines - blank_lines - comment_lines

        # Token-level grammar analysis
        tokens = []
        for ln in lines:
            tokens.extend(ln.split())

        try:
            predictions = angel.predict(
                tokens[:20], domain="computational", horizon=5
            )
        except Exception:
            predictions = []

        # Pattern detection heuristics
        patterns_found = []
        code_lower = code.lower()
        pattern_signatures = {
            "recursion": ["def ", "return ", "self."],
            "iteration": ["for ", "while "],
            "conditional": ["if ", "elif ", "else:"],
            "error_handling": ["try:", "except ", "raise "],
            "class_definition": ["class "],
            "function_definition": ["def "],
            "list_comprehension": ["[", "for ", " in "],
            "context_manager": ["with "],
            "decorator": ["@"],
            "lambda": ["lambda "],
            "import": ["import ", "from "],
        }
        for pattern, signatures in pattern_signatures.items():
            if all(sig in code_lower for sig in signatures):
                patterns_found.append(pattern)

        # Check for common issues
        issues = []
        if code_lines > 0 and comment_lines / max(code_lines, 1) < 0.1:
            issues.append("Low comment density (< 10%)")
        for i, ln in enumerate(lines, 1):
            if len(ln) > 120:
                issues.append(f"Line {i} exceeds 120 characters ({len(ln)} chars)")
                break
        if "except:" in code or "except Exception:" in code:
            issues.append("Broad exception handling detected")
        if "global " in code:
            issues.append("Global variable usage detected")

        # Grammar predictions
        grammar_insights = []
        for pred in predictions[:5]:
            grammar_insights.append({
                "rule": pred.get("rule", "?"),
                "prediction": str(pred.get("predicted", "?")),
                "confidence": pred.get("confidence", 0.0),
            })

        return {
            "metrics": {
                "total_lines": total_lines,
                "code_lines": code_lines,
                "blank_lines": blank_lines,
                "comment_lines": comment_lines,
                "token_count": len(tokens),
            },
            "patterns": patterns_found,
            "issues": issues,
            "grammar_analysis": grammar_insights,
            "source": "local_glm",
        }

    def refactor(self, code: str, instruction: str) -> str:
        """Refactor code following grammatical rules.

        Args:
            code: Source code to refactor.
            instruction: What refactoring to perform.

        Returns:
            Refactored code.
        """
        if self._provider is not None:
            return self._provider.generate(
                f"Refactor this code according to the instruction.\n\n"
                f"Instruction: {instruction}\n\n"
                f"Code:\n```\n{code}\n```\n\n"
                f"Output only the refactored code.",
                system=(
                    "You are a code refactoring assistant. Apply the "
                    "requested change and output only the modified code. "
                    "Preserve functionality. Use clean style."
                ),
                temperature=0.2,
                max_tokens=2048,
            )

        # Local: provide grammar-based refactoring suggestions
        analysis = self.analyze_code(code)
        issues = analysis.get("issues", [])
        patterns = analysis.get("patterns", [])

        lines = ["# MKAngel GLM Refactoring Report"]
        lines.append(f"# Instruction: {instruction}")
        lines.append(f"# Patterns detected: {', '.join(patterns) or 'none'}")
        if issues:
            lines.append(f"# Issues found: {', '.join(issues)}")
        lines.append("#")
        lines.append(
            "# The local GLM can identify structural patterns and issues"
        )
        lines.append(
            "# but cannot rewrite code. Configure an API provider for"
        )
        lines.append("# full refactoring capability.")
        lines.append("#")
        lines.append("# Original code follows:")
        lines.append("")
        lines.append(code)
        return "\n".join(lines)

    def explain_code(self, code: str) -> str:
        """Explain code using the grammar model.

        Args:
            code: Source code to explain.

        Returns:
            Human-readable explanation.
        """
        if self._provider is not None:
            return self._provider.generate(
                f"Explain this code clearly and concisely. Cover what it does, "
                f"how it works, and any notable patterns.\n\n```\n{code}\n```",
                system=(
                    "You are a code explanation assistant. Explain code clearly "
                    "for a developer audience. Be concise but thorough."
                ),
                temperature=0.3,
                max_tokens=1024,
            )

        # Local grammar-based explanation
        analysis = self.analyze_code(code)
        m = analysis.get("metrics", {})
        patterns = analysis.get("patterns", [])
        issues = analysis.get("issues", [])
        grammar = analysis.get("grammar_analysis", [])

        parts = []
        parts.append("Code Analysis (GLM Computational Grammar)")
        parts.append("=" * 42)
        parts.append("")

        parts.append("Structure:")
        parts.append(f"  {m.get('code_lines', 0)} lines of code")
        parts.append(f"  {m.get('comment_lines', 0)} comment lines")
        parts.append(f"  {m.get('token_count', 0)} tokens")
        parts.append("")

        if patterns:
            parts.append("Patterns detected:")
            for p in patterns:
                parts.append(f"  - {p.replace('_', ' ').title()}")
            parts.append("")

        if grammar:
            parts.append("Grammar derivations:")
            for g in grammar:
                parts.append(
                    f"  - {g['rule']}: {g['prediction']} "
                    f"(confidence {g['confidence']:.2f})"
                )
            parts.append("")

        if issues:
            parts.append("Potential issues:")
            for issue in issues:
                parts.append(f"  ! {issue}")
            parts.append("")

        parts.append(
            "For a natural-language explanation, configure an API provider."
        )

        return "\n".join(parts)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _derive_skeleton(
    description: str, language: str, predictions: list[dict],
) -> str:
    """Derive a code skeleton from description and grammar predictions."""
    desc_lower = description.lower()

    # Detect intent from description keywords
    if language == "python":
        return _python_skeleton(desc_lower, predictions)
    elif language in ("javascript", "js", "typescript", "ts"):
        return _js_skeleton(desc_lower, predictions)
    else:
        return _generic_skeleton(desc_lower, language, predictions)


def _python_skeleton(desc: str, predictions: list[dict]) -> str:
    """Generate a Python code skeleton."""
    lines = []

    if "class" in desc:
        # Infer a class name from description
        name = _extract_name(desc, "class")
        lines.append(f"class {name}:")
        lines.append(f'    """TODO: {desc}"""')
        lines.append("")
        lines.append("    def __init__(self):")
        lines.append("        pass")
        lines.append("")
        lines.append("    def __repr__(self):")
        lines.append(f'        return f"{name}()"')
    elif any(kw in desc for kw in ("function", "func", "def", "method")):
        name = _extract_name(desc, "function")
        lines.append(f"def {name}():")
        lines.append(f'    """TODO: {desc}"""')
        lines.append("    pass")
    elif any(kw in desc for kw in ("sort", "search", "find", "filter")):
        name = _extract_name(desc, "function")
        lines.append(f"def {name}(data):")
        lines.append(f'    """TODO: {desc}"""')
        lines.append("    result = []")
        lines.append("    for item in data:")
        lines.append("        # TODO: implement logic")
        lines.append("        result.append(item)")
        lines.append("    return result")
    elif "api" in desc or "server" in desc or "endpoint" in desc:
        lines.append("import http.server")
        lines.append("import json")
        lines.append("")
        lines.append("class Handler(http.server.BaseHTTPRequestHandler):")
        lines.append("    def do_GET(self):")
        lines.append("        self.send_response(200)")
        lines.append('        self.send_header("Content-Type", "application/json")')
        lines.append("        self.end_headers()")
        lines.append(f'        # TODO: {desc}')
        lines.append('        self.wfile.write(json.dumps({{"status": "ok"}}).encode())')
    else:
        name = _extract_name(desc, "function")
        lines.append(f"def {name}():")
        lines.append(f'    """TODO: {desc}"""')
        lines.append("    # TODO: implement")
        lines.append("    pass")

    return "\n".join(lines)


def _js_skeleton(desc: str, predictions: list[dict]) -> str:
    """Generate a JavaScript code skeleton."""
    name = _extract_name(desc, "function")
    if "class" in desc:
        return (
            f"class {name} {{\n"
            f"  constructor() {{\n"
            f"    // TODO: {desc}\n"
            f"  }}\n"
            f"}}"
        )
    return (
        f"function {name}() {{\n"
        f"  // TODO: {desc}\n"
        f"}}"
    )


def _generic_skeleton(desc: str, language: str, predictions: list[dict]) -> str:
    """Generate a generic code skeleton."""
    return (
        f"// Language: {language}\n"
        f"// TODO: {desc}\n"
        f"// Implement the logic here.\n"
    )


def _extract_name(desc: str, kind: str) -> str:
    """Try to extract a sensible name from the description."""
    # Remove common filler words
    skip = {
        "a", "an", "the", "that", "which", "to", "for", "of", "in",
        "with", "and", "or", "is", "are", "was", "were", "be", "been",
        "create", "make", "build", "write", "generate", "implement",
        "function", "class", "method", "def", "func",
    }
    words = [w for w in desc.split() if w not in skip and w.isalpha()]
    if not words:
        return f"my_{kind}"

    # Take up to 3 significant words, snake_case
    name_parts = words[:3]
    return "_".join(name_parts)
